
name: Deploy synced docs

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout woo-docs-build repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clone woocommerce repo (source)
        run: |
          git clone --depth=1 --branch=docusaurus-docs-prep https://github.com/woocommerce/woocommerce.git /tmp/source
          ls -la /tmp/source/docs

      - name: Install dependencies
        working-directory: docs/_docu-tools
        run: npm ci

      - name: Build documentation
        working-directory: docs/_docu-tools
        run: npm run build
      
      - name: Commit docs
        working-directory: docs/_docu-tools/build
        run: |
          BRANCH_NAME="docs-build-$(date +'%Y%m%d-%H%M%S')"
          git init
          git remote add origin https://x-access-token:${GH_PAT}@github.com/wpcomvip/woocommerce-woo-docs-multi-com.git
          git fetch origin develop
          git checkout -b $BRANCH_NAME
          cd plugins/docu-loader/docs-build
          cp -r */ plugins/docu-loader/docs-build/
          git add plugins/docu-loader/docs-build/
          git commit -m "Update documentation build"
          git push origin $BRANCH_NAME
