
name: Deploy synced docs

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout woo-docs-build repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clone woocommerce repo (source)
        run: |
          git clone --depth=1 --branch=docusaurus-docs-prep https://github.com/woocommerce/woocommerce.git /tmp/source
          ls -la /tmp/source/docs

      - name: Install dependencies
        working-directory: docs/_docu-tools
        run: npm ci

      - name: Build documentation
        working-directory: docs/_docu-tools
        run: npm run build
      - name: Deploy docs to target repo
        run: |
            BRANCH_NAME="docs-build-$(date +'%Y%m%d-%H%M%S')"
            TARGET_REPO="wpcomvip/woocommerce-woo-docs-multi-com.git"
            
            git clone https://x-access-token:${DEPLOY_PAT}@github.com/${TARGET_REPO} /tmp/target-repo
            cd /tmp/target-repo
            
            git checkout develop
            git pull
            git checkout -b $BRANCH_NAME
            
            mkdir -p plugins/docu-loader/docs-build
            cp -r ${GITHUB_WORKSPACE}/docs/_docu-tools/build/* plugins/docu-loader/docs-build/
            
            git add plugins/docu-loader/docs-build/
            git commit -m "Update documentation build from $(date)"
            git push origin $BRANCH_NAME
        env:
            DEPLOY_PAT: ${{ secrets.DEPLOY_PAT }}