name: Deploy synced docs

on:
  # schedule:
  #   - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone woocommerce repo (source)
        run: |
          git clone --depth=1 --branch=docusaurus-docs-prep https://github.com/woocommerce/woocommerce.git /tmp/source
          ls -la /tmp/source/docs

      - name: Install dependencies and build docs
        working-directory: /tmp/source/docs/_docu-tools
        run: |
          npm install
          npm run build

      - name: Deploy docs to target repo
        id: deploy
        run: |
            BRANCH_NAME="docs-build-$(date +'%Y%m%d-%H%M%S')"
            
            git clone https://x-access-token:${DEPLOY_PAT}@github.com/${TARGET_REPO} /tmp/target-repo
            cd /tmp/target-repo
            
            git checkout develop
            git pull origin develop
            
            # Create and switch to new branch
            git checkout -b $BRANCH_NAME
            
            git config --global user.email "github-actions@github.com"
            git config --global user.name "GitHub Actions"
            
            mkdir -p plugins/docu-loader/docs-build
            cp -r /tmp/source/docs/_docu-tools/build/* plugins/docu-loader/docs-build/
            
            git add plugins/docu-loader/docs-build/
            git commit -m "Update documentation build from $(date)"
            git push origin $BRANCH_NAME

            gh pr create --title "Update documentation build" --body "This PR contains the latest documentation build updates." --reviewer piinthecloud
        env:
            DEPLOY_PAT: ${{ secrets.DEPLOY_PAT }}
            GH_TOKEN: ${{ secrets.DEPLOY_PAT}}
            TARGET_REPO: ${{ secrets.TARGET_REPO}}
