name: Test deploy

on:
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone woocommerce repo (source)
        run: |
          git clone --branch=trunk https://github.com/woocommerce/woocommerce.git /tmp/source

      - name: Check if /docs has changed
        working-directory: /tmp/source
        run: |
          # Fetch the last commit hash from remote
          git fetch origin trunk
          PREV_COMMIT=$(git rev-parse HEAD~1)
          echo "Comparing with previous commit: $PREV_COMMIT"

          # Check for changes in the /docs folder
          DOC_CHANGES=$(git diff --name-only $PREV_COMMIT HEAD -- docs/)

          if [ -z "$DOC_CHANGES" ]; then
            echo "No changes in /docs detected. Exiting."
            exit 0
          else
            echo "Docs have changed:"
            echo "$DOC_CHANGES"
            echo "$DOC_CHANGES" > /tmp/changed-doc-files.txt
          fi

      - name: Deploy docs to target repo
        run: |
          # Generate PR body from changed source files
          PR_BODY="This PR contains documentation updates based on changes in the WooCommerce /docs directory.%0A%0A**Changed source files:**%0A"
          while IFS= read -r file; do
            PR_BODY+="%0A- \`${file}\`"
          done < /tmp/changed-doc-files.txt

          # Preview PR body for testing
          echo -e "🧪 Previewing PR body:\n"
          echo -e "$PR_BODY"


        env:
          DEPLOY_PAT: ${{ secrets.DEPLOY_PAT }}
          GH_TOKEN: ${{ secrets.DEPLOY_PAT }}
          TARGET_REPO: ${{ secrets.TARGET_REPO }}
